name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  push-to-artifactory:
    name: Test and publish snapshot to artifactory
    runs-on: ubuntu-latest

    steps:
      - name: Checkout github branch
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
          cache: maven

      - name: Check version from pom.xml
        id: check_version
        run: |
          PROJECT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "PROJECT_VERSION: ${PROJECT_VERSION}"
          if [[ ${PROJECT_VERSION} != *-SNAPSHOT ]]; then
            echo "Error: version must be suffixed with '-SNAPSHOT'. Concrete versions can only be released from master branch"
            exit 1
          fi

      - name: Test
        run: mvn --no-transfer-progress clean verify

      - name: Install gpg key
        run: cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | base64 --decode | gpg --batch --import

      - name: Maven deploy
        run: mvn --no-transfer-progress --batch-mode -DskipTests deploy -P release
        env:
          MAVEN_USERNAME: ${{ secrets.D11_NEXUS_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.D11_NEXUS_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
