name: Google Java Formatter

on:
  pull_request:
    types:
      - synchronize
      - opened
    paths:
      - 'src/**'
  push:
    branches:
      - master

jobs:
  formatting:
    name: Google Java Formatter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
          overwrite-settings: false

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.2

      - name: Run fmt-plugin check goal
        run: mvn com.spotify.fmt:fmt-maven-plugin:2.20:check
